<?xml version="1.0"?>
<testResults>
  <FitNesseVersion>v20151230</FitNesseVersion>
  <rootPath>CalcPage</rootPath>
    <executionLog>
    <testSystem>slim:fitnesse.slim.SlimService</testSystem>
    <command>python -m waferslim.server --syspath fitnesse_files\ 8093</command>
    <exitCode>1</exitCode>
    <stdOut></stdOut>
    <stdErr>Traceback (most recent call last):
  File "&lt;frozen runpy&gt;", line 198, in _run_module_as_main
  File "&lt;frozen runpy&gt;", line 88, in _run_code
  File "C:\Users\johnm\AppData\Local\Programs\Python\Python311\Lib\site-packages\waferslim-1.0.2-py3.11.egg\waferslim\server.py", line 164, in &lt;module&gt;
    start_server()
  File "C:\Users\johnm\AppData\Local\Programs\Python\Python311\Lib\site-packages\waferslim-1.0.2-py3.11.egg\waferslim\server.py", line 161, in start_server
    WaferSlimServer(options).serve_forever()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\johnm\AppData\Local\Programs\Python\Python311\Lib\site-packages\waferslim-1.0.2-py3.11.egg\waferslim\server.py", line 86, in __init__
    super().__init__(server_address, SlimRequestHandler)
  File "C:\Users\johnm\AppData\Local\Programs\Python\Python311\Lib\socketserver.py", line 456, in __init__
    self.server_bind()
  File "C:\Users\johnm\AppData\Local\Programs\Python\Python311\Lib\socketserver.py", line 472, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
</stdErr>
  </executionLog>
  <finalCounts>
    <right>0</right>
    <wrong>0</wrong>
    <ignores>0</ignores>
    <exceptions>0</exceptions>
  </finalCounts>
  <totalRunTimeInMillis>2927</totalRunTimeInMillis>
</testResults>

